# Generated by Django 5.0.1 on 2024-01-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinform',
            name='purpose',
            field=models.CharField(choices=[('S', '-------'), ('E', 'Enquiry'), ('P', 'Place Order'), ('R', 'Return')], default='S', max_length=1),
        ),
    ]
